export const industries_en = [
  {
    label: "Autos (Sales and Service)",
    items: [
      { label: "Boat Sales", value: 1 },
      { label: "Car Washes", value: 2 },
      { label: "Fuel Dispensers", value: 3 },
      { label: "Towing Services", value: 4 },
      { label: "Truck Stop", value: 5 },
    ],
  },
  {
    label: "Building Services",
    items: [
      { label: "A C And Heating Contractors", value: 6 },
      { label: "Carpentry Contractors", value: 7 },
      { label: "Electrical Contractors", value: 8 },
      { label: "General Contractors", value: 9 },
      { label: "Other Building Services", value: 10 },
      { label: "Special Trade Contractors", value: 11 },
      { label: "Telecom Equipment", value: 12 },
      { label: "Telecom Services", value: 13 },
    ],
  },
  {
    label: "Digital Products",
    items: [
      { label: "Apps", value: 14 },
      { label: "Blogs And Written Content", value: 15 },
      { label: "Books", value: 16 },
      { label: "Games", value: 17 },
      { label: "Music Or Other Media", value: 18 },
      { label: "Other Digital Goods", value: 19 },
      { label: "Software As A Service", value: 20 },
    ],
  },
  {
    label: "Education",
    items: [
      { label: "Business And Secretarial Schools", value: 21 },
      { label: "Child Care Services", value: 22 },
      { label: "Colleges Or Universities", value: 23 },
      { label: "Elementary Or Secondary Schools", value: 24 },
      { label: "Other Educational Services", value: 25 },
      { label: "Vocational Schools And Trade Schools", value: 26 },
    ],
  },
  {
    label: "Entertainment And Recreation",
    items: [
      { label: "Amusement Parks, Carnivals, Or Circuses", value: 27 },
      { label: "Betting Or Fantasy Sports", value: 28 },
      { label: "Event Ticketing", value: 29 },
      { label: "Fortune Tellers", value: 30 },
      { label: "Lotteries", value: 31 },
      { label: "Movie Theaters", value: 32 },
      { label: "Musicians, Bands, Or Orchestras", value: 33 },
      { label: "Online Gambling", value: 34 },
      { label: "Other Entertainment And Recreation", value: 35 },
      { label: "Recreational Camps", value: 36 },
      { label: "Sports Forecasting Or Prediction Services", value: 37 },
      { label: "Tourist Attractions", value: 38 },
    ],
  },
  {
    label: "Financial Services",
    items: [
      { label: "Check Cashing", value: 39 },
      { label: "Collections Agencies", value: 40 },
      { label: "Cryptocurrencies", value: 41 },
      { label: "Currency Exchanges", value: 42 },
      { label: "Digital Wallets", value: 43 },
      { label: "Financial Information And Research", value: 44 },
      { label: "Insurance", value: 45 },
      { label: "Investment Services", value: 46 },
      { label: "Loans Or Lending", value: 47 },
      { label: "Money Orders", value: 48 },
      { label: "Money Services Or Transmission", value: 49 },
      { label: "Other Financial Institutions", value: 50 },
      { label: "Personal Fundraising Or Crowdfunding", value: 51 },
      { label: "Security Brokers Or Dealers", value: 52 },
      { label: "Virtual Currencies", value: 53 },
      { label: "Wire Transfers", value: 54 },
    ],
  },
  {
    label: "Food And Drink",
    items: [
      { label: "Bars And Nightclubs", value: 55 },
      { label: "Caterers", value: 56 },
      { label: "Fast Food Restaurants", value: 57 },
      { label: "Grocery Stores", value: 58 },
      { label: "Other Food And Dining", value: 59 },
      { label: "Restaurants And Nightlife", value: 60 },
    ],
  },
  {
    label: "Medical Services",
    items: [
      { label: "Assisted Living", value: 61 },
      { label: "Chiropractors", value: 62 },
      { label: "Dentists And Orthodontists", value: 63 },
      { label: "Doctors And Physicians", value: 64 },
      { label: "Health And Wellness Coaching", value: 65 },
      { label: "Hospitals", value: 66 },
      { label: "Medical Devices", value: 67 },
      { label: "Medical Laboratories", value: 68 },
      { label: "Medical Organizations", value: 69 },
      { label: "Mental Health Services", value: 70 },
      { label: "Nursing Or Personal Care Facilities", value: 71 },
      { label: "Opticians And Eyeglasses", value: 72 },
      { label: "Optometrists and Ophthalmologists", value: 73 },
      { label: "Osteopaths", value: 74 },
      { label: "Other Medical Services", value: 75 },
      { label: "Personal Fundraising Or Crowdfunding", value: 76 },
      { label: "Podiatrists and Chiropodists", value: 77 },
      { label: "Telemedicine And Telehealth", value: 78 },
      { label: "Veterinary Services", value: 79 },
    ],
  },
  {
    label: "Membership Organizations",
    items: [
      { label: "Charities Or Social Service Organizations", value: 80 },
      { label: "Civic, Fraternal, Or Social Associations", value: 81 },
      { label: "Country Clubs", value: 82 },
      { label: "Other Membership Organizations", value: 83 },
      { label: "Political Organizations", value: 84 },
      { label: "Religious Organizations", value: 85 },
    ],
  },
  {
    label: "Personal Services",
    items: [
      { label: "Counseling Services", value: 86 },
      { label: "Dating Services", value: 87 },
      { label: "Funeral Services", value: 88 },
      { label: "Health And Beauty Spas", value: 89 },
      { label: "Health And Wellness Coaching", value: 90 },
      { label: "Landscaping Services", value: 91 },
      { label: "Laundry Or Cleaning Services", value: 92 },
      { label: "Massage Parlors", value: 93 },
      { label: "Other Personal Services", value: 94 },
      { label: "Photography Studios", value: 95 },
      { label: "Salons Or Barbers", value: 96 },
    ],
  },
  {
    label: "Professional Services",
    items: [
      { label: "Accounting, Auditing, Or Tax Prep", value: 97 },
      { label: "Attorneys And Lawyers", value: 98 },
      { label: "Auto Services", value: 99 },
      { label: "Bail Bonds", value: 100 },
      { label: "Bankruptcy Services", value: 101 },
      { label: "Car Rentals", value: 102 },
      { label: "Car Sales", value: 103 },
      { label: "Computer Repair", value: 104 },
      { label: "Consulting", value: 105 },
      { label: "Credit Counseling Or Credit Repair", value: 106 },
      { label: "Debt Reduction Services", value: 107 },
      { label: "Digital Marketing", value: 108 },
      { label: "Employment Agencies", value: 109 },
      { label: "Government Services", value: 110 },
      { label: "Lead Generation", value: 111 },
      { label: "Mortgage Consulting Services", value: 112 },
      { label: "Other Business Services", value: 113 },
      { label: "Other Marketing Services", value: 114 },
      { label: "Printing and Publishing", value: 115 },
      { label: "Protective Or Security Services", value: 116 },
      { label: "Software As A Service", value: 117 },
      { label: "Telemarketing", value: 118 },
      { label: "Testing Laboratories", value: 119 },
      { label: "Utilities", value: 120 },
      { label: "Warranty Services", value: 121 },
    ],
  },
  {
    label: "Regulated And Age-Restricted Products",
    items: [
      { label: "Accessories For Tobacco And Marijuana", value: 122 },
      { label: "Adult Content Or Services", value: 123 },
      { label: "Alcohol", value: 124 },
      { label: "Marijuana Dispensaries", value: 125 },
      { label: "Marijuana-related Products", value: 126 },
      { label: "Pharmacies Or Pharmaceuticals", value: 127 },
      { label: "Supplements Or Nutraceuticals", value: 128 },
      { label: "Tobacco Or Cigars", value: 129 },
      { label: "Vapes, E-cigarettes, E-juice Or Related Products", value: 130 },
      { label: "Weapons Or Munitions", value: 131 },
    ],
  },
  {
    label: "Retail",
    items: [
      { label: "Accessories", value: 132 },
      { label: "Antiques", value: 133 },
      { label: "Auto Parts And Accessories", value: 134 },
      { label: "Beauty Products", value: 135 },
      { label: "Clothing And Accessories", value: 136 },
      { label: "Convenience Stores", value: 137 },
      { label: "Designer Products", value: 138 },
      { label: "Flowers", value: 139 },
      { label: "Hardware Stores", value: 140 },
      { label: "Home Electronics", value: 141 },
      { label: "Home Goods And Furniture", value: 142 },
      { label: "Other Merchandise", value: 143 },
      { label: "Shoes", value: 144 },
      { label: "Software", value: 145 },
    ],
  },
  {
    label: "Transportation",
    items: [
      { label: "Airlines And Air Carriers", value: 146 },
      { label: "Commuter Transportation", value: 147 },
      { label: "Courier Services", value: 148 },
      { label: "Cruise Lines", value: 149 },
      { label: "Freight Forwarders", value: 150 },
      { label: "Other Transportation Services", value: 151 },
      { label: "Parking Lots", value: 152 },
      { label: "Ridesharing", value: 153 },
      { label: "Shipping Or Forwarding", value: 154 },
      { label: "Taxis And Limos", value: 155 },
      { label: "Travel Agencies", value: 156 },
    ],
  },
  {
    label: "Travel And Lodging",
    items: [
      { label: "Hotels, Inns, Or Motels", value: 157 },
      { label: "Other Travel And Lodging", value: 158 },
      { label: "Property Rentals", value: 159 },
      { label: "Timeshares", value: 160 },
      { label: "Trailer Parks and Campgrounds", value: 161 },
    ],
  },
] as const;

export const industries_fr = [
  {
    label: "Automobiles (Vente et Service)",
    items: [
      { label: "Vente de Bateaux", value: 1 },
      { label: "Lavage de Voitures", value: 2 },
      { label: "Distributeurs de Carburant", value: 3 },
      { label: "Services de Remorquage", value: 4 },
      { label: "Aire de Repos pour Camions", value: 5 },
    ],
  },
  {
    label: "Services de Construction",
    items: [
      { label: "Entrepreneurs en Climatisation et Chauffage", value: 6 },
      { label: "Entrepreneurs en Charpenterie", value: 7 },
      { label: "Entrepreneurs Électriciens", value: 8 },
      { label: "Entrepreneurs Généraux", value: 9 },
      { label: "Autres Services de Construction", value: 10 },
      { label: "Entrepreneurs en Métiers Spécialisés", value: 11 },
      { label: "Équipement de Télécommunications", value: 12 },
      { label: "Services de Télécommunications", value: 13 },
    ],
  },
  {
    label: "Produits Numériques",
    items: [
      { label: "Applications", value: 14 },
      { label: "Blogs et Contenu Écrit", value: 15 },
      { label: "Livres", value: 16 },
      { label: "Jeux", value: 17 },
      { label: "Musique ou Autres Médias", value: 18 },
      { label: "Autres Biens Numériques", value: 19 },
      { label: "Logiciels en tant que Service", value: 20 },
    ],
  },
  {
    label: "Éducation",
    items: [
      { label: "Écoles de Commerce et Secrétariat", value: 21 },
      { label: "Services de Garde d'Enfants", value: 22 },
      { label: "Collèges ou Universités", value: 23 },
      { label: "Écoles Primaires ou Secondaires", value: 24 },
      { label: "Autres Services Éducatifs", value: 25 },
      { label: "Écoles Professionnelles et Techniques", value: 26 },
    ],
  },
  {
    label: "Divertissement et Loisirs",
    items: [
      { label: "Parcs d'Attractions, Carnavals ou Cirques", value: 27 },
      { label: "Pari ou Sports Fantaisie", value: 28 },
      { label: "Billetterie pour Événements", value: 29 },
      { label: "Voyants", value: 30 },
      { label: "Loteries", value: 31 },
      { label: "Cinémas", value: 32 },
      { label: "Musiciens, Groupes ou Orchestres", value: 33 },
      { label: "Jeux d'Argent en Ligne", value: 34 },
      { label: "Autres Divertissements et Loisirs", value: 35 },
      { label: "Camps de Vacances", value: 36 },
      { label: "Services de Prévisions ou Prédictions Sportives", value: 37 },
      { label: "Attractions Touristiques", value: 38 },
    ],
  },
  {
    label: "Services Financiers",
    items: [
      { label: "Encaissement de Chèques", value: 39 },
      { label: "Agences de Recouvrement", value: 40 },
      { label: "Cryptomonnaies", value: 41 },
      { label: "Échanges de Monnaie", value: 42 },
      { label: "Portefeuilles Numériques", value: 43 },
      { label: "Informations et Recherche Financière", value: 44 },
      { label: "Assurance", value: 45 },
      { label: "Services d'Investissement", value: 46 },
      { label: "Prêts ou Financement", value: 47 },
      { label: "Mandats", value: 48 },
      { label: "Services ou Transmission d'Argent", value: 49 },
      { label: "Autres Institutions Financières", value: 50 },
      { label: "Collecte de Fonds ou Crowdfunding", value: 51 },
      { label: "Courtiers ou Négociants en Valeurs Mobilières", value: 52 },
      { label: "Monnaies Virtuelles", value: 53 },
      { label: "Transferts d'Argent", value: 54 },
    ],
  },
  {
    label: "Alimentation et Boissons",
    items: [
      { label: "Bars et Discothèques", value: 55 },
      { label: "Traiteurs", value: 56 },
      { label: "Restaurants de Restauration Rapide", value: 57 },
      { label: "Magasins d'Alimentation", value: 58 },
      { label: "Autres Aliments et Restauration", value: 59 },
      { label: "Restaurants et Vie Nocturne", value: 60 },
    ],
  },
  {
    label: "Services Médicaux",
    items: [
      { label: "Vivi d'Assistance", value: 61 },
      { label: "Chiropracteurs", value: 62 },
      { label: "Dentistes et Orthodontistes", value: 63 },
      { label: "Médecins et Chirurgiens", value: 64 },
      { label: "Coaching en Santé et Bien-Être", value: 65 },
      { label: "Hôpitaux", value: 66 },
      { label: "Dispositifs Médicaux", value: 67 },
      { label: "Laboratoires Médicaux", value: 68 },
      { label: "Organisations Médicales", value: 69 },
      { label: "Services de Santé Mentale", value: 70 },
      {
        label: "Établissements de Soins ou d'Assistance Personnelle",
        value: 71,
      },
      { label: "Opticiens et Lunettes", value: 72 },
      { label: "Optométristes et Ophtalmologistes", value: 73 },
      { label: "Ostéopathes", value: 74 },
      { label: "Autres Services Médicaux", value: 75 },
      { label: "Collecte de Fonds ou Crowdfunding", value: 76 },
      { label: "Podologues et Chiropodistes", value: 77 },
      { label: "Télémédecine et Télésanté", value: 78 },
      { label: "Services Vétérinaires", value: 79 },
    ],
  },
  {
    label: "Organisations de Membres",
    items: [
      {
        label: "Œuvres de Charité ou Organisations de Services Sociaux",
        value: 80,
      },
      { label: "Associations Civiques, Fraternelles ou Sociales", value: 81 },
      { label: "Clubs de Campagne", value: 82 },
      { label: "Autres Organisations de Membres", value: 83 },
      { label: "Organisations Politiques", value: 84 },
      { label: "Organisations Religieuses", value: 85 },
    ],
  },
  {
    label: "Services Personnels",
    items: [
      { label: "Services de Conseil", value: 86 },
      { label: "Services de Rencontres", value: 87 },
      { label: "Services Funéraires", value: 88 },
      { label: "Spas de Santé et de Beauté", value: 89 },
      { label: "Coaching en Santé et Bien-Être", value: 90 },
      { label: "Services de Paysagisme", value: 91 },
      { label: "Services de Blanchisserie ou de Nettoyage", value: 92 },
      { label: "Salons de Massage", value: 93 },
      { label: "Autres Services Personnels", value: 94 },
      { label: "Studios de Photographie", value: 95 },
      { label: "Salons ou Coiffeurs", value: 96 },
    ],
  },
  {
    label: "Services Professionnels",
    items: [
      { label: "Comptabilité, Audit ou Préparation des Impôts", value: 97 },
      { label: "Avocats et Juristes", value: 98 },
      { label: "Services Automobile", value: 99 },
      { label: "Cautionnement", value: 100 },
      { label: "Services de Faillite", value: 101 },
      { label: "Location de Voitures", value: 102 },
      { label: "Vente de Voitures", value: 103 },
      { label: "Réparation d'Ordinateurs", value: 104 },
      { label: "Consultation", value: 105 },
      { label: "Conseil en Crédit ou Réparation de Crédit", value: 106 },
      { label: "Services de Réduction de Dette", value: 107 },
      { label: "Marketing Numérique", value: 108 },
      { label: "Agences d'Emploi", value: 109 },
      { label: "Services Gouvernementaux", value: 110 },
      { label: "Génération de Leads", value: 111 },
      { label: "Services de Conseil Hypothécaire", value: 112 },
      { label: "Autres Services Aux Entreprises", value: 113 },
      { label: "Autres Services de Marketing", value: 114 },
      { label: "Impression et Édition", value: 115 },
      { label: "Services de Protection ou de Sécurité", value: 116 },
      { label: "Logiciels en tant que Service", value: 117 },
      { label: "Téléprospection", value: 118 },
      { label: "Laboratoires d'Essai", value: 119 },
      { label: "Services Publics", value: 120 },
      { label: "Services de Garantie", value: 121 },
    ],
  },
  {
    label: "Produits Réglementés et Restreints par Âge",
    items: [
      { label: "Accessoires pour Tabac et Marijuana", value: 122 },
      { label: "Contenu ou Services pour Adultes", value: 123 },
      { label: "Alcool", value: 124 },
      { label: "Dispensaires de Marijuana", value: 125 },
      { label: "Produits Liés à la Marijuana", value: 126 },
      { label: "Pharmacies ou Produits Pharmaceutiques", value: 127 },
      { label: "Suppléments ou Nutraceutiques", value: 128 },
      { label: "Tabac ou Cigares", value: 129 },
      {
        label: "Vapes, E-cigarettes, E-juice ou Produits Connexes",
        value: 130,
      },
      { label: "Armes ou Munitions", value: 131 },
    ],
  },
  {
    label: "Commerce de Détail",
    items: [
      { label: "Accessoires", value: 132 },
      { label: "Antiquités", value: 133 },
      { label: "Pièces et Accessoires pour Automobiles", value: 134 },
      { label: "Produits de Beauté", value: 135 },
      { label: "Vêtements et Accessoires", value: 136 },
      { label: "Magasins de Commodités", value: 137 },
      { label: "Produits de Designer", value: 138 },
      { label: "Fleurs", value: 139 },
      { label: "Magasins de Matériel", value: 140 },
      { label: "Électronique Domestique", value: 141 },
      { label: "Articles pour la Maison et Meubles", value: 142 },
      { label: "Autres Marchandises", value: 143 },
      { label: "Chaussures", value: 144 },
      { label: "Logiciels", value: 145 },
    ],
  },
  {
    label: "Transport",
    items: [
      { label: "Compagnies Aériennes et Transporteurs Aériens", value: 146 },
      { label: "Transport Commuter", value: 147 },
      { label: "Services de Messagerie", value: 148 },
      { label: "Lignes de Croisière", value: 149 },
      { label: "Transit de Fret", value: 150 },
      { label: "Autres Services de Transport", value: 151 },
      { label: "Parkings", value: 152 },
      { label: "Covoiturage", value: 153 },
      { label: "Expédition ou Transit", value: 154 },
      { label: "Taxis et Limousines", value: 155 },
      { label: "Agences de Voyage", value: 156 },
    ],
  },
  {
    label: "Voyage et Hébergement",
    items: [
      { label: "Hôtels, Auberges ou Motels", value: 157 },
      { label: "Autres Voyage et Hébergement", value: 158 },
      { label: "Locations de Propriétés", value: 159 },
      { label: "Timeshares", value: 160 },
      { label: "Parcs à Caravanes et Campings", value: 161 },
    ],
  },
] as const;
